name: student_paddy_mobile
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+36

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_svg: ^0.23.0+1
  device_preview: ^1.0.0
  provider: ^6.0.0
  http: ^0.13.3
  font_awesome_flutter: ^9.1.0
  readmore: ^2.1.0
  google_fonts: ^2.1.0
  fluttertoast: ^8.0.7
  intl: ^0.17.0
  path_provider: ^2.0.7
  flutter_local_notifications: ^9.1.2
  firebase_core: ^1.10.0
  google_sign_in: ^5.2.3
  firebase_messaging: ^11.1.0
  flutter_spinkit: ^5.1.0
  firebase_auth: ^3.1.1
  get: ^4.6.1
  persistent_bottom_nav_bar: ^4.0.2
  webview_flutter: ^2.0.13
  country_picker: ^2.0.8
  url_launcher: ^6.0.10
  dropdown_search: ^1.0.3
  image_picker: ^0.8.4+1
  photo_view: ^0.13.0
  flutter_link_previewer: ^2.6.0
  simple_url_preview: ^3.0.1
  timeago: ^3.1.0
  shared_preferences: ^2.0.8
  adaptive_dialog: ^1.2.0
  collection: ^1.15.0
  flutter_html: ^2.2.1
  file_picker: ^4.2.4
  pull_to_refresh: ^2.0.0
  search_choices: ^2.0.14
  multi_select_flutter: ^4.0.0
  flutter_summernote: ^1.0.0
  html_editor_enhanced: ^2.0.0
  socket_io_client: ^2.0.0-beta.4-nullsafety.0
  dart_nats: ^0.3.5
  share_plus: ^3.0.4
  cached_network_image: ^3.2.0
  stream_transform: ^2.0.0
  overlay_support: ^1.2.1
  new_version: ^0.2.3
  firebase_dynamic_links: ^4.0.3
  badges: ^2.0.2
  auto_size_text: ^3.0.0
  html: ^0.15.0
  rflutter_alert: ^2.0.4
  shimmer: ^2.0.0
  bubble: ^1.2.1
  sticky_headers: ^0.1.8
  video_player: ^2.2.13
  flutter_requery: ^0.1.8
  flutter_inappwebview: ^5.3.2
  flutter_custom_tabs: ^1.0.4
  eventify: ^1.0.0
  sign_in_with_apple: ^3.3.0
  better_player: ^0.0.81
  string_validator: ^0.3.0
  flutter_widget_from_html: ^0.8.5
  rich_text_controller: ^1.4.0
  hive: ^2.1.0
  flutter_mentions: ^2.0.1
  flutter_parsed_text: ^2.2.1
  archive: ^3.3.0
  flutter_image_compress: ^1.1.0
  wechat_assets_picker: ^7.1.2
  markdown: ^5.0.0
  event_bus: ^2.0.0

dev_dependencies:
  flutter_native_splash: ^1.3.2
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/pngs/
    - assets/svgs/
  fonts:
    - family: pt_sans
      fonts:
        - asset: assets/fonts/PT_Sans/PTSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/PT_Sans/PTSans-Bold.ttf
          weight: 600
      
    - family:  CustomIcons
      fonts:
       - asset: assets/fonts/CustomIcons.ttf

    - family:  NavigationIcons
      fonts:
       - asset: assets/fonts/NavigationIcons.ttf


    - family: Graphik
      fonts:
        - asset: assets/fonts/Graphik/GraphikThin.otf
          weight: 100
        - asset: assets/fonts/Graphik/GraphikExtralight.otf
          weight: 200
        - asset: assets/fonts/Graphik/GraphikLight.otf
          weight: 300
        - asset: assets/fonts/Graphik/GraphikRegular.otf
          weight: 400
        - asset: assets/fonts/Graphik/GraphikMedium.otf
          weight: 500
        - asset: assets/fonts/Graphik/GraphikSemibold.otf
          weight: 600
        - asset: assets/fonts/Graphik/GraphikBold.otf
          weight: 700
        - asset: assets/fonts/Graphik/GraphikBold.otf
          weight: 800
        - asset: assets/fonts/Graphik/GraphikBlack.otf
          weight: 900

    - family: Avenir
      fonts:
        - asset: assets/fonts/Avenir/Avenir-LT-Std-35-Light.ttf
          weight: 300
        - asset: assets/fonts/Avenir/Avenir-LT-Std-45-Book.ttf
          weight: 400
        - asset: assets/fonts/Avenir/Avenir-LT-Std-55-Roman.ttf
          weight: 500
        - asset: assets/fonts/Avenir/Avenir-LT-Std-65-Medium.ttf
          weight: 600
        - asset: assets/fonts/Avenir/Avenir-LT-Std-85-Heavy.ttf
          weight: 800
        - asset: assets/fonts/Avenir/Avenir-LT-Std-95-Black.ttf
          weight: 900

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
