/// Flutter icons NavigationIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  NavigationIcons
///      fonts:
///       - asset: fonts/NavigationIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class NavigationIcons {
  NavigationIcons._();

  static const _kFontFam = 'NavigationIcons';
  static const String? _kFontPkg = null;

  static const IconData community = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dubs = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData account = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData topics = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
